# -*- coding: utf-8 -*-
"""multiple_linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lp16gstLKT6DfhTPNsbwdG3BgEjWDZIO
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

from google.colab import files
uploaded = files.upload()

import zipfile
import os

zip_path = "BrainTumorYolov11.zip"  # تأكد من اسم الملف
extract_path = "/content/brain_tumor_dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("✅ تم فك الضغط عن البيانات بنجاح")

data_yaml = """
train: /content/brain_tumor_dataset/images/train
val: /content/brain_tumor_dataset/images/val
test: /content/brain_tumor_dataset/images/test

nc: 4
names: ['glioma', 'meningioma', 'pituitary', 'no_tumor']
"""

with open("data.yaml", "w") as f:
    f.write(data_yaml)

print("✅ تم إنشاء ملف الإعدادات data.yaml بنجاح")

from ultralytics import YOLO

# تحميل نموذج YOLO
model = YOLO("yolov8n.pt")

# تدريب النموذج
model.train(data="/content/brain_tumor_dataset/BrainTumorYolov11/data.yaml", epochs=10, imgsz=640)

# تقييم النموذج
metrics = model.val()

# عرض الأداء (precision, recall, mAP)
print(metrics)

# اختبار صورة جديدة
results = model.predict("/content/brain_tumor_dataset/BrainTumorYolov11/test/images/1046_jpg.rf.26dd526422308d6d9e989d3308a9ee03.jpg", save=True)

# عرض النتيجة
results[0].plot()  # عرض النتيجة الأولى في القائمة